[package]
name = "battrs"
version = "0.1.0"
authors = ["Danny Hadley <dadleyy@gmail.com>"]
edition = "2018"

[lib]
name = "battrs"
path = "src/lib.rs"

[[bin]]
name = "battrs"
path = "src/bin/main.rs"

[dependencies]
