name: gh.build
on: [push]
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update-stable
        run: rustup toolchain install stable
      - name: test
        run: cargo test
